"""Train the eye open/closed classifier and export it for the ESP32-S3.

Input : MRL Eye Dataset extracted under ml/data/mrlEyes_2018_01/<subject>/<image>.png
        file name: subject_image_gender_glasses_eyestate_reflections_lighting_sensor.png
        eyestate 0 = closed, 1 = open
Output: ml/out/eye_model_int8.tflite and src/model_data.cpp (C array for TFLite Micro)
        The model outputs P(closed) via softmax over [open, closed].

Usage:
    py -3.10 ml/train_eye.py                 # full training
    py -3.10 ml/train_eye.py --untrained     # export a random model to test the firmware path
"""

import argparse
import random
from pathlib import Path

import numpy as np
import tensorflow as tf

ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data" / "mrlEyes_2018_01"
OUT_DIR = ROOT / "out"
MODEL_CPP = ROOT.parent / "src" / "model_data.cpp"
IMG = 96
CLASSES = ["open", "closed"]


def list_samples():
    samples = []
    for path in DATA_DIR.rglob("*.png"):
        parts = path.stem.split("_")
        if len(parts) < 8:
            continue
        subject, eyestate = parts[0], int(parts[4])
        label = 1 if eyestate == 0 else 0  # 1 = closed
        samples.append((str(path), label, subject))
    return samples


def split_by_subject(samples, seed=42):
    # Split by person, not by image, otherwise accuracy is inflated
    subjects = sorted({s for _, _, s in samples})
    random.Random(seed).shuffle(subjects)
    n_test = max(1, len(subjects) // 6)
    n_val = max(1, len(subjects) // 6)
    test_s = set(subjects[:n_test])
    val_s = set(subjects[n_test:n_test + n_val])
    pick = lambda keep: [(p, l) for p, l, s in samples if keep(s)]
    return (pick(lambda s: s not in test_s and s not in val_s),
            pick(lambda s: s in val_s),
            pick(lambda s: s in test_s))


def load_image(path, label):
    img = tf.io.decode_png(tf.io.read_file(path), channels=1)
    img = tf.image.resize(img, (IMG, IMG))
    return img, label


def augment(img, label):
    img = tf.image.random_flip_left_right(img)
    img = tf.image.random_brightness(img, 40.0)
    img = tf.image.random_contrast(img, 0.7, 1.3)
    img = tf.clip_by_value(img, 0.0, 255.0)
    return img, label


def make_ds(items, training, batch=128):
    paths = [p for p, _ in items]
    labels = [l for _, l in items]
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if training:
        ds = ds.shuffle(len(items), reshuffle_each_iteration=True)
    ds = ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        ds = ds.map(augment, num_parallel_calls=tf.data.AUTOTUNE)
    return ds.batch(batch).prefetch(tf.data.AUTOTUNE)


def build_model():
    # Pixels 0..255 in, rescaled inside the model so the firmware feeds raw grayscale
    inp = tf.keras.Input((IMG, IMG, 1))
    x = tf.keras.layers.Rescaling(1 / 127.5, offset=-1)(inp)
    base = tf.keras.applications.MobileNetV2(
        input_shape=(IMG, IMG, 1), alpha=0.35, include_top=False, weights=None)
    # Default BN momentum 0.999 is too slow when training from scratch: the moving
    # stats lag far behind and the model predicts one class at inference time
    for layer in base.layers:
        if isinstance(layer, tf.keras.layers.BatchNormalization):
            layer.momentum = 0.9
    x = base(x)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dropout(0.2)(x)
    out = tf.keras.layers.Dense(len(CLASSES), activation="softmax")(x)
    return tf.keras.Model(inp, out)


def convert_int8(model, representative):
    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = representative
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    return conv.convert()


def write_model(tflite, note):
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "eye_model_int8.tflite").write_bytes(tflite)
    lines = [", ".join(f"0x{b:02x}" for b in tflite[i:i + 16]) for i in range(0, len(tflite), 16)]
    MODEL_CPP.write_text(
        f"// Generated by ml/train_eye.py{note}, do not edit\n"
        "#include \"model_data.h\"\n\n"
        "alignas(16) const unsigned char g_eye_model[] = {\n  "
        + ",\n  ".join(lines)
        + "\n};\n"
        f"const unsigned int g_eye_model_len = {len(tflite)};\n")
    print(f"Exported {len(tflite) / 1024:.1f} KB -> {MODEL_CPP}")


def eval_int8(test_items):
    interp = tf.lite.Interpreter(model_path=str(OUT_DIR / "eye_model_int8.tflite"))
    interp.allocate_tensors()
    inp, out = interp.get_input_details()[0], interp.get_output_details()[0]
    in_scale, in_zero = inp["quantization"]
    correct = 0
    for path, label in test_items:
        img, _ = load_image(path, label)
        q = np.clip(np.round(img.numpy() / in_scale + in_zero), -128, 127).astype(np.int8)
        interp.set_tensor(inp["index"], q[None])
        interp.invoke()
        correct += int(np.argmax(interp.get_tensor(out["index"])[0]) == label)
    print(f"INT8 test accuracy: {correct / len(test_items):.4f} on {len(test_items)} images")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs", type=int, default=15)
    ap.add_argument("--untrained", action="store_true")
    args = ap.parse_args()

    model = build_model()
    model.summary()

    if args.untrained:
        def fake_rep():
            for _ in range(10):
                yield [tf.random.uniform((1, IMG, IMG, 1), 0, 255)]
        write_model(convert_int8(model, fake_rep), " --untrained (random weights, firmware test only)")
        return

    samples = list_samples()
    if not samples:
        raise SystemExit(f"No images found under {DATA_DIR}")
    train, val, test = split_by_subject(samples)
    print(f"train {len(train)}  val {len(val)}  test {len(test)}")

    model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
                  loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    OUT_DIR.mkdir(exist_ok=True)
    model.fit(make_ds(train, True), validation_data=make_ds(val, False), epochs=args.epochs,
              callbacks=[
                  tf.keras.callbacks.ModelCheckpoint(str(OUT_DIR / "best.h5"), save_best_only=True,
                                                     monitor="val_accuracy"),
                  tf.keras.callbacks.ReduceLROnPlateau(patience=2, factor=0.5),
                  tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True),
              ])
    print("Float test:", model.evaluate(make_ds(test, False), verbose=0))
    random.Random(0).shuffle(train)

    def representative():
        for path, label in train[:300]:
            img, _ = load_image(path, label)
            yield [tf.expand_dims(img, 0)]

    write_model(convert_int8(model, representative), "")
    eval_int8(test)


if __name__ == "__main__":
    main()
